### ISSUE TITLE
False attribute name 'decklidstatus' Senor.xxxxxx_lock

### ISSUE THREAD

**Issue by johiodo** [ReneNulschDE/mbapi2020#176]
Hi,
selecting this sensor in automations with the attribute name "Deck Lid" results in a not working trigger. The selectable name is not corresponding with the name "decklidstatus"

![image](https://github.com/ReneNulschDE/mbapi2020/assets/114515106/e5bc11dc-b827-4284-bd09-b7767c24b22e)

![image](https://github.com/ReneNulschDE/mbapi2020/assets/114515106/dd0edcae-b8d1-4c7d-84f7-b6ab3c195535)

**Comment by ReneNulschDE** [comment]
Hi @johiodo,

could you please first check if the attribute decklidstatus is changing to true when you open the decklid. We had this topic a few quarters ago that not each car is reporting this correctly.

I just created a simple automation:
![image](https://github.com/ReneNulschDE/mbapi2020/assets/33263735/85f37162-46fa-4da9-ba0a-809ebea9f704)

![image](https://github.com/ReneNulschDE/mbapi2020/assets/33263735/af91f2e7-1959-4869-b0f7-15d25ea55d49)

After saving it. I opened the decklid and the automation started.

![image](https://github.com/ReneNulschDE/mbapi2020/assets/33263735/543f0337-59a9-4a84-bc33-ea863e3f60d0)


here again my automation config:
```
id: '1705862416787'
alias: DeckLid Checker
description: ''
trigger:
  - platform: state
    entity_id:
      - sensor.l_so127e_lock
    attribute: decklidstatus
condition: []
action:
  - service: persistent_notification.create
    data:
      message: Decklid changes
mode: single
```
