### ISSUE TITLE
Remote Lock/Unlock failing

### ISSUE THREAD

**Issue by snappa2000** [ReneNulschDE/mbapi2020#199]
### The problem

When trying to lock/unlock the below error message appears.
**The code for lock.a45s_lock doesn't match pattern ^\d{4}$**
This was working a few weeks ago, but has stopped working for both cars we have registered.

### What version of MBAPI2020 do use?

v0.10.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-mbapi2020-594f6c57d804f715a66be00eeffb357d.json](https://github.com/ReneNulschDE/mbapi2020/files/14226946/config_entry-mbapi2020-594f6c57d804f715a66be00eeffb357d.json)

### Example YAML snippet

```yaml
Snippet below from main YAML for button:

show_name: true
show_icon: true
type: button
tap_action:
  action: toggle
show_state: true
entity: lock.a45s_lock
hold_action:
   action: toggle
```

### Anything in the logs that might be useful for us?

```txt
2024-02-10 09:20:25.610 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139663534629824] The code for lock.a45s_lock doesn't match pattern ^\d{4}$
```
