### ISSUE TITLE
Calling the configure max soc service switches the charging program to standard

### ISSUE THREAD

**Issue by josephdouce** [ReneNulschDE/mbapi2020#229]
### The problem

Calling the configure max soc service switches the charging program to standard.

Is this the desired behaviour? 

### What version of MBAPI2020 do use?

v0.13.0

### What was the last working version of MBAPI2020?

v0.13.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-mbapi2020-8214be536ccc11f2e4386e0cdfb082d6.json](https://github.com/ReneNulschDE/mbapi2020/files/15387098/config_entry-mbapi2020-8214be536ccc11f2e4386e0cdfb082d6.json)

### Example YAML snippet

```yaml
alias: Charge Automation
description: ""
trigger:
  - platform: time_pattern
    minutes: "01"
  - platform: time_pattern
    minutes: "31"
condition:
  - condition: state
    entity_id: sensor.car_charging_program
    state: Home
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: >-
              sensor.octopus_energy_electricity_acc_current_rate
            above: 0.15
        sequence:
          - service: mbapi2020.battery_max_soc_configure
            data:
              vin: !secret
              max_soc: "50"
      - conditions:
          - condition: numeric_state
            entity_id: >-
              sensor.octopus_energy_electricity_acc_current_rate
            below: 0.15
        sequence:
          - service: mbapi2020.battery_max_soc_configure
            data:
              vin: !secret
              max_soc: "100"
mode: single
```

### Additional information

I was hoping to use the "Home" profile to enable me to automate my dumb chargers, I can simply use standard however I would expect the update max soc to update the current charge program.
