### ISSUE TITLE
Premclimate switch in Apple Home not fully working

### ISSUE THREAD

**Issue by NoLeeDa** [ReneNulschDE/mbapi2020#289]
### The problem

Hi Rene, I used the entity "switch._licenseplate__vorklimatisierung" to be forwarded to Apple Home via HomeKit Bridge. In HomeAssistant, the buttons for starting and stopping work. Unfortunately this switch in Apple Home does not start or stop the preclimate function, but, when I start or stop the function using the mercedes app, the state of the switch in Home changes correctly to active or inactive. What do I need to change in order to activate or stop the function from Home?

Best regards

David

### What version of MBAPI2020 do use?

v0.21.0

### What type of installation are you running?

Home Assistant Container

**Comment by NoLeeDa** [comment]
Hi Rene, how do I export the debug log?

**Comment by KevinNL1999** [comment]
@ReneNulschDE 
The preclimate is not working for me either. I clicked the preclimate_start button multiple times, but unfortunately, nothing seems to happen.

In the Mercedes app there is kind of a strange procedure:
1. Activate preclimate first time -> sets the departure time.
2. Activate preclimate second time -> start preclimate directly.

I do not know of this procedure for the Mercedes app has anything to do with the component problem.

The warning in the HA logging:

Logger: custom_components.mbapi2020.client
Bron: custom_components/mbapi2020/client.py:839
integratie: MercedesME 2020 (documentatie, problemen)
Eerst voorgekomen: 06:57:28 (8 gebeurtenissen)
Laatst gelogd: 06:57:47

Car action: PRECONDSTART failed. error_code: 4051, error_message: None
Car action: PRECONDSTART failed. error_code: RIS_COULD_NOT_SEND_COMMAND, error_message: None

**Comment by ReneNulschDE** [comment]
@KevinNL1999 : Is this a new error or has this never worked? The error comes from the MB Server and is a general "ProcessingFailed"... Could you share a [diagnostic report](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics) and a [debug log](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging) (Replace MQTT in the Docs with MBAPI2020? --> mbdev.i289@nulsch.de

**Comment by KevinNL1999** [comment]
@ReneNulschDE I haven’t tested this before, so unfortunately, I can’t confirm if it would have worked previously. I’ve sent you the diagnostic report and debug log.

**Comment by ReneNulschDE** [comment]
@NoLeeDa: Could you share a [diagnostic report](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics) and a [debug log](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging) (Replace MQTT in the Docs with MBAPI2020 and Homekit? --> [mbdev.i289@nulsch.de](mailto:mbdev.i289@nulsch.de)

**Comment by ReneNulschDE** [comment]
@KevinNL1999: As shared via email:

My guess is that your wagon does not support immediate start of pre-conditioning. The official app solves this by simply setting the departure time to “in 15 minutes” so that the car starts the air conditioning automatically. Translated into a HomeAssistant component, this would be the start of the action “mbapi2020.preheat_start_departure_time”
 
I have tried to find a difference in the master data of the car, unfortunately without success - therefore I cannot adapt the code so that the switches work for you.
 
But here is one option:
 
An automation that starts pre-conditioning (Replace XXX_YOUR_VIN_XXX with your VIN):
 ```

alias: action_start_preclimate_15min
description: “”
triggers: []
conditions: []
actions:
  - action: mbapi2020.preheat_start_departure_time
    data:
      vin: XXX_YOUR_VIN_XXX
      time: |
        {{ now().hour * 60 + now().minute + 15 }}
mode: single
 
```
And a button that you can add in the frontend and click on it to start the automation and thus the preconditioning.
 ```

type: button
name: Start preconditioning
icon: mdi:car-seat-heater
tap_action:
  action: call-service
  service: automation.trigger
  service_data:
    entity_id: automation.action_start_preclimate_15min
 
```
I hope this helps for now.
