### ISSUE TITLE
Trunk and cowl not working

### ISSUE THREAD

**Issue by salvatoreboemia** [ReneNulschDE/mbapi2020#299]
### The problem

Hello

I have an issue with the trunk open image and cowl

Trunk code:
```
mba_trunk:
        friendly_name: "Trunk"
        icon_template: mdi:car-door
        value_template: >
          {% if state_attr('sensor.myCar_lock', 'doorlockstatusdecklid') %}
            unlocked
          {% elif state_attr('sensor.myCar_lock', 'decklidstatus') %}
            open
          {% else %}
            closed
          {% endif %}
```

YAML

```
- type: image
    entity: sensor.mba_trunk
    state_image:
      open: local/177000_trunk_openNEW.png
      unlocked: local/177000_trunk_unlock.png
      closed: null
    style:
      top: 0%
      left: 0%
      transform: none
```

<img width="326" alt="394773336-a3a88b1a-7e5a-4b83-9a2f-c6315a94b8b4" src="https://github.com/user-attachments/assets/3931f838-7015-4e75-9d17-d426ef65eee7" />

Do you know why?

Thanks

### What version of MBAPI2020 do use?

v021.1

### What was the last working version of MBAPI2020?

v021.1

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
Please share the diagnostic report.

**Comment by salvatoreboemia** [comment]
> Please share the diagnostic report.

How?

I didn't see any error. Just no icon

Or I need to enable in HA diagnostic?

Thank

**Comment by ReneNulschDE** [comment]
From my perspective is the template config wrong. Here is an adjusted template code.

```
          {% if state_attr('sensor.myCar_lock', 'doorlockstatusdecklid') and not state_attr('sensor.myCar_lock', 'decklidstatus') %}
            unlocked
          {% elif state_attr('sensor.myCar_lock', 'decklidstatus') and state_attr('sensor.myCar_lock', 'doorlockstatusdecklid') %}
            open
          {% else %}
            closed
          {% endif %}
```

**Comment by ReneNulschDE** [comment]
To check the cowl, please share the [diagnostic report](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics).
Replace MQTT in the Docs with MBAPI2020

**Comment by salvatoreboemia** [comment]
> To check the cowl, please share the [diagnostic report](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics).
> 
> Replace MQTT in the Docs with MBAPI2020

Hi @ReneNulschDE 

Now The trunk with your code works fine

![image](https://github.com/user-attachments/assets/d71d782c-a0d0-45a0-9044-0d88cb7b1848)

For The cowl I not have a code like trunk

Here the log

**Comment by ReneNulschDE** [comment]
Thanks for the log. Unfortunately, this is a debug log and not the diagnostic log. Please check again this [doc](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics) (Replace MQTT with MBAPI2020).

**Comment by salvatoreboemia** [comment]
> Thanks for the log. Unfortunately, this is a debug log and not the diagnostic log. Please check again this [doc](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics) (Replace MQTT with MBAPI2020).

I downloaded now from here

<img width="200" alt="Screenshot 2024-12-23 at 17 07 25" src="https://github.com/user-attachments/assets/00d3c16a-e229-4980-ad0c-8c4564a20a88" />


let me know if you need something else for the cowl thanks


[config_entry-mbapi2020-c332b880ea0f9968fad88efa616ac67d.json](https://github.com/user-attachments/files/18231281/config_entry-mbapi2020-c332b880ea0f9968fad88efa616ac67d.json)

**Comment by ReneNulschDE** [comment]
You can use the attribute "engineHoodStatus" of the sensor "lock" to visualize the cowl/engine hood.

Create a sensor:


```
      mba_cowl:
        friendly_name: "Cowl"
        icon_template: mdi:car-door
        value_template: >
          {% if state_attr('sensor.myCar_lock', 'engineHoodStatus') %}
            open
          {% else %}
            closed
          {% endif %}
```

Image:


```
- type: image
    entity: sensor.mba_cowl
    state_image:
      open: local/177000_cowl.png
      closed: null
    style:
      top: 0%
      left: 0%
      transform: none
```
