### ISSUE TITLE
State attribute precondActive is not updated

### ISSUE THREAD

**Issue by Thomas55555** [ReneNulschDE/mbapi2020#8]
Hello Rene,
nice work that you are doing with your integration. Works pretty good.
I wanted to build a template switch for the preconditioning. The problem is, that I used the state attribute `precondActive` in the electric_range sensor as value_template. See the configuration:
```yaml
switch:
  - platform: template
    switches:
      vorklimatisierung:
      value_template: "{{ is_state_attr('sensor.xxx_range_electric', 'precondActive', true) }}"
        turn_on:
          service: mbapi2020.preheat_start
          data:
            vin: W1K205xxxx
        turn_off:
          service: mbapi2020.preheat_stop
          data:
            vin: W1K205xxxx
```
But `precondActive` always stays on `false` even if the preconditioning is working. `chargingactive` for example gets updated, if I turn on the preconditioning an the car is plugged in.
Any idea, why this is not getting updated?
Are you planning to stay on the services for the commands or will you integrate switch and lock entities?
